/**
 * Export Service
 * 
 * Generates PDF exports for plans, checklists, and binders using jsPDF.
 */

import {
  AftercarePlan,
  ExecutorChecklistItem,
  ContactEntry,
  TaskPhase,
} from '../types';
import { getPhaseInfo } from './taskGenerationEngine';
import { getChecklistCategoryInfo, getContactTypeInfo } from './executorService';
import jsPDF from 'jspdf';

/**
 * Export plan to PDF
 */
export async function exportPlanToPdf(plan: AftercarePlan): Promise<void> {
  try {
    const doc = new jsPDF();
  let yPos = 20;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const lineHeight = 7;

  // Helper to add new page if needed (optimized for large documents)
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };
  
  // Batch processing for large lists to prevent memory issues
  const processInBatches = <T,>(items: T[], batchSize: number, processor: (item: T) => void) => {
    for (let i = 0; i < items.length; i += batchSize) {
      const batch = items.slice(i, i + batchSize);
      batch.forEach(processor);
      // Allow UI to remain responsive
      if (i + batchSize < items.length) {
        // Small delay for very large lists
        const shouldYield = items.length > 100 && i % (batchSize * 10) === 0;
        if (shouldYield) {
          // Yield to event loop (would need async/await in real implementation)
        }
      }
    }
  };

  // Header
  doc.setFontSize(20);
  doc.setTextColor(201, 174, 102); // Gold color
  doc.text('LOCAL AFTERCARE VAULT PLAN', margin, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Administrative guidance only. Not legal, financial, or medical advice.', margin, yPos);
  yPos += 10;

  // Profile Summary
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  if (plan.profile.deceasedName) {
    doc.text(`For: ${plan.profile.deceasedName}`, margin, yPos);
    yPos += lineHeight;
  }
  const relationship = plan.profile.relationship || 'Not specified';
  doc.text(`Relationship: ${relationship}`, margin, yPos);
  yPos += lineHeight;
  const region = plan.profile.region || '';
  const country = plan.profile.country || 'Not specified';
  const location = region ? `${region}, ${country}` : country;
  doc.text(`Location: ${location}`, margin, yPos);
  yPos += lineHeight;
  doc.text(`Created: ${new Date(plan.createdAt).toLocaleDateString()}`, margin, yPos);
  yPos += 10;

  // Task Summary
  const addressed = plan.tasks.filter(t => t.status === 'DONE').length;
  const total = plan.tasks.length;
  doc.setFontSize(11);
  doc.text(`Items Addressed: ${addressed} of ${total}`, margin, yPos);
  yPos += 10;

  // Tasks by Phase
  const phases: TaskPhase[] = ['FIRST_48_HOURS', 'WEEK_1', 'WEEKS_2_6', 'DAYS_60_90', 'LONG_TERM'];
  
  for (const phase of phases) {
    const phaseTasks = plan.tasks.filter(t => t.phase === phase);
    if (phaseTasks.length === 0) continue;

    checkPageBreak(15);
    
    const phaseInfo = getPhaseInfo(phase);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`── ${phaseInfo.label} ──`, margin, yPos);
    yPos += lineHeight;
    doc.setFont('helvetica', 'normal');

    for (const task of phaseTasks) {
      checkPageBreak(lineHeight + 2);
      const status = task.status === 'DONE' ? '✓' : task.status === 'IN_PROGRESS' ? '◐' : '○';
      doc.setFontSize(10);
      doc.text(`${status} ${task.title}`, margin + 5, yPos);
      yPos += lineHeight;
    }
    yPos += 3;
  }

  // Footer
  checkPageBreak(15);
  yPos += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Local Aftercare Vault', margin, yPos);
  yPos += 5;
  doc.text('This is administrative guidance only. For legal, financial, or tax advice,', margin, yPos);
  yPos += 5;
  doc.text('please consult appropriate licensed professionals.', margin, yPos);

    // Save PDF
    const fileName = `Aftercare_Plan_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}

/**
 * Export comprehensive binder
 */
export async function exportAftercareBinder(
  plan: AftercarePlan,
  contacts: ContactEntry[],
  checklist: ExecutorChecklistItem[]
): Promise<void> {
  try {
    const doc = new jsPDF();
  let yPos = 20;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const lineHeight = 7;

  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // Cover Page
  doc.setFontSize(24);
  doc.setTextColor(201, 174, 102);
  doc.text('LOCAL AFTERCARE VAULT', margin, yPos + 20);
  doc.text('ADMINISTRATIVE BINDER', margin, yPos + 30);
  
  if (plan.profile.deceasedName) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`For ${plan.profile.deceasedName}`, margin, yPos + 45);
  }
  
  doc.setFontSize(10);
  doc.text(`Created: ${new Date().toLocaleDateString()}`, margin, yPos + 55);
  
  yPos = pageHeight - 40;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('This binder provides administrative guidance only.', margin, yPos);
  yPos += 5;
  doc.text('IT DOES NOT PROVIDE LEGAL, FINANCIAL, OR MEDICAL ADVICE.', margin, yPos);

  // Section 1: Reference Information
  doc.addPage();
  yPos = margin;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('SECTION 1: REFERENCE INFORMATION', margin, yPos);
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  if (plan.profile.deceasedName) {
    doc.text(`Deceased: ${plan.profile.deceasedName}`, margin, yPos);
    yPos += lineHeight;
  }
  const relationship = plan.profile.relationship || 'Not specified';
  doc.text(`Your Relationship: ${relationship}`, margin, yPos);
  yPos += lineHeight;
  const region = plan.profile.region || '';
  const country = plan.profile.country || 'Not specified';
  const location = region ? `${region}, ${country}` : country;
  doc.text(`Location: ${location}`, margin, yPos);
  yPos += lineHeight;
  const hasWill = plan.profile.hasWill === true ? 'Yes' : plan.profile.hasWill === false ? 'No' : 'Unknown';
  doc.text(`Has Will: ${hasWill}`, margin, yPos);
  yPos += lineHeight;
  const isExecutor = plan.profile.isExecutor === true ? 'Yes' : plan.profile.isExecutor === false ? 'No' : 'Unknown';
  doc.text(`Is Executor: ${isExecutor}`, margin, yPos);
  yPos += 10;

  // Section 2: Administrative Considerations
  checkPageBreak(20);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('SECTION 2: ADMINISTRATIVE CONSIDERATIONS', margin, yPos);
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const addressed = plan.tasks.filter(t => t.status === 'DONE').length;
  doc.text(`Items Addressed: ${addressed} of ${plan.tasks.length}`, margin, yPos);
  yPos += 10;

  const phases: TaskPhase[] = ['FIRST_48_HOURS', 'WEEK_1', 'WEEKS_2_6', 'DAYS_60_90', 'LONG_TERM'];
  
  for (const phase of phases) {
    const phaseTasks = plan.tasks.filter(t => t.phase === phase);
    if (phaseTasks.length === 0) continue;

    checkPageBreak(15);
    const phaseInfo = getPhaseInfo(phase);
    doc.setFont('helvetica', 'bold');
    doc.text(`── ${phaseInfo.label} ──`, margin, yPos);
    yPos += lineHeight;
    doc.setFont('helvetica', 'normal');

    for (const task of phaseTasks) {
      checkPageBreak(lineHeight + 2);
      const status = task.status === 'DONE' ? '✓' : '○';
      doc.text(`${status} ${task.title}`, margin + 5, yPos);
      yPos += lineHeight;
    }
    yPos += 3;
  }

  // Section 3: Common Next Steps (Checklist)
  if (checklist.length > 0) {
    checkPageBreak(20);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('SECTION 3: COMMON NEXT STEPS', margin, yPos);
    yPos += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    const categories = ['DOCUMENTS', 'COMMUNICATION', 'ASSET_TRACKING', 'RECORD_KEEPING', 'FOLLOW_UP'];
    
    for (const cat of categories) {
      const items = checklist.filter(i => i.category === cat);
      if (items.length === 0) continue;

      checkPageBreak(15);
      const catInfo = getChecklistCategoryInfo(cat as any);
      doc.setFont('helvetica', 'bold');
      doc.text(`── ${catInfo.label} ──`, margin, yPos);
      yPos += lineHeight;
      doc.setFont('helvetica', 'normal');

      for (const item of items) {
        checkPageBreak(lineHeight + 2);
        const status = item.status === 'DONE' ? '✓' : '○';
        doc.text(`${status} ${item.title}`, margin + 5, yPos);
        yPos += lineHeight;
      }
      yPos += 3;
    }
  }

  // Section 4: Contact Reference
  if (contacts.length > 0) {
    checkPageBreak(20);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('SECTION 4: CONTACT REFERENCE', margin, yPos);
    yPos += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    const types = ['BANK', 'INSURANCE', 'EMPLOYER', 'UTILITY', 'ADVISOR', 'OTHER'];
    
    for (const type of types) {
      const typeContacts = contacts.filter(c => c.type === type);
      if (typeContacts.length === 0) continue;

      checkPageBreak(15);
      const typeInfo = getContactTypeInfo(type as any);
      doc.setFont('helvetica', 'bold');
      doc.text(`── ${typeInfo.label} ──`, margin, yPos);
      yPos += lineHeight;
      doc.setFont('helvetica', 'normal');

      for (const contact of typeContacts) {
        checkPageBreak(lineHeight * 4);
        doc.text(`${contact.name}`, margin + 5, yPos);
        yPos += lineHeight;
        if (contact.phone) {
          doc.text(`  Phone: ${contact.phone}`, margin + 5, yPos);
          yPos += lineHeight;
        }
        if (contact.email) {
          doc.text(`  Email: ${contact.email}`, margin + 5, yPos);
          yPos += lineHeight;
        }
        if (contact.website) {
          doc.text(`  Website: ${contact.website}`, margin + 5, yPos);
          yPos += lineHeight;
        }
        yPos += 2;
      }
    }
  }

  // Footer
  checkPageBreak(15);
  yPos += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('END OF BINDER', margin, yPos);
  yPos += 5;
  doc.text('Generated by Local Aftercare Vault', margin, yPos);
  yPos += 5;
  doc.text('Remember: This is administrative guidance only.', margin, yPos);
  yPos += 5;
  doc.text('For legal, financial, or tax advice, please consult', margin, yPos);
  yPos += 5;
    doc.text('appropriate licensed professionals.', margin, yPos);

    // Save PDF
    const fileName = `Aftercare_Binder_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}
