/**
 * Export Service
 * 
 * Generates PDF exports for plans, checklists, and binders using jsPDF.
 */

import {
  AftercarePlan,
  ExecutorChecklistItem,
  ContactEntry,
  TaskPhase,
  UploadedDocument,
} from '../types';
import { getPhaseInfo } from './taskGenerationEngine';
import { getChecklistCategoryInfo, getContactTypeInfo, getExecutorChecklistCategoryOrder } from './executorService';
import jsPDF from 'jspdf';

export interface ExportBinderOptions {
  includeNotesPerItem?: boolean;
  includeKeyDocumentsList?: boolean;
}

/**
 * Export plan to PDF
 */
export async function exportPlanToPdf(plan: AftercarePlan): Promise<void> {
  try {
    const doc = new jsPDF();
  let yPos = 20;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const lineHeight = 7;

  // Helper to add new page if needed (optimized for large documents)
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };
  

  // Header
  doc.setFontSize(20);
  doc.setTextColor(201, 174, 102); // Gold color
  doc.text('LOCAL AFTERCARE VAULT PLAN', margin, yPos);
  yPos += 10;

  // Profile Summary
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  if (plan.profile.deceasedName) {
    doc.text(`For: ${plan.profile.deceasedName}`, margin, yPos);
    yPos += lineHeight;
  }
  const relationship = plan.profile.relationship || 'Not specified';
  doc.text(`Relationship: ${relationship}`, margin, yPos);
  yPos += lineHeight;
  const region = plan.profile.region || '';
  const country = plan.profile.country || 'Not specified';
  const location = region ? `${region}, ${country}` : country;
  doc.text(`Location: ${location}`, margin, yPos);
  yPos += lineHeight;
  doc.text(`Created: ${new Date(plan.createdAt).toLocaleDateString()}`, margin, yPos);
  yPos += 10;

  // Task Summary
  const addressed = plan.tasks.filter(t => t.status === 'DONE').length;
  const total = plan.tasks.length;
  doc.setFontSize(11);
  doc.text(`Items Addressed: ${addressed} of ${total}`, margin, yPos);
  yPos += 10;

  // Tasks by Phase
  const phases: TaskPhase[] = ['FIRST_48_HOURS', 'WEEK_1', 'WEEKS_2_6', 'DAYS_60_90', 'LONG_TERM'];
  
  for (const phase of phases) {
    const phaseTasks = plan.tasks.filter(t => t.phase === phase);
    if (phaseTasks.length === 0) continue;

    checkPageBreak(15);
    
    const phaseInfo = getPhaseInfo(phase);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`── ${phaseInfo.label} ──`, margin, yPos);
    yPos += lineHeight;
    doc.setFont('helvetica', 'normal');

    for (const task of phaseTasks) {
      checkPageBreak(lineHeight + 2);
      const status = task.status === 'DONE' ? '✓' : task.status === 'IN_PROGRESS' ? '◐' : '○';
      doc.setFontSize(10);
      doc.text(`${status} ${task.title}`, margin + 5, yPos);
      yPos += lineHeight;
    }
    yPos += 3;
  }

  // Footer — single disclaimer at bottom, small font
  checkPageBreak(15);
  yPos += 5;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by AfterPassing Guide', margin, yPos);
  yPos += 5;
  doc.text('This material is provided for organizational guidance only and does not constitute legal, financial, or medical advice.', margin, yPos, { maxWidth: doc.internal.pageSize.width - margin * 2 });

    // Save PDF
    const fileName = `Aftercare_Plan_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}

/** Draw confidential watermark on current page (centered, rotated, light). */
function addConfidentialWatermark(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(48);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(200, 200, 200);
  const text = 'CONFIDENTIAL';
  doc.text(text, pageWidth / 2, pageHeight / 2, { align: 'center', angle: 45 });
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
}

/**
 * Export Estate Binder — professional handoff PDF for attorneys, courts, beneficiaries.
 * Clean, neutral formatting. Confidential watermark on every page. Disclaimer included at bottom.
 */
export async function exportAftercareBinder(
  plan: AftercarePlan,
  contacts: ContactEntry[],
  checklist: ExecutorChecklistItem[],
  options?: ExportBinderOptions,
  documents?: UploadedDocument[]
): Promise<void> {
  try {
    const doc = new jsPDF();
    let yPos = 20;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const lineHeight = 7;
    const includeNotes = options?.includeNotesPerItem ?? true;
    const includeDocs = options?.includeKeyDocumentsList ?? true;

    const checkPageBreak = (requiredSpace: number) => {
      if (yPos + requiredSpace > pageHeight - margin) {
        doc.addPage();
        yPos = margin;
      }
    };

    // Cover — neutral
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text('Estate Binder', margin, yPos + 20);
    doc.setFontSize(12);
    if (plan.profile.deceasedName) {
      doc.text(`For ${plan.profile.deceasedName}`, margin, yPos + 32);
    }
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Created: ${new Date().toLocaleDateString()}`, margin, yPos + 42);

    yPos = pageHeight - 28;
    doc.setFontSize(8);
    doc.text('This material is provided for organizational guidance only and does not constitute legal, financial, or medical advice.', margin, yPos, { maxWidth: doc.internal.pageSize.width - margin * 2 });

    let sectionNum = 1;

    // Section: Reference information
    doc.addPage();
    yPos = margin;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(`SECTION ${sectionNum}: REFERENCE INFORMATION`, margin, yPos);
    yPos += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    if (plan.profile.deceasedName) {
      doc.text(`Deceased: ${plan.profile.deceasedName}`, margin, yPos);
      yPos += lineHeight;
    }
    const relationship = plan.profile.relationship || 'Not specified';
    doc.text(`Relationship: ${relationship}`, margin, yPos);
    yPos += lineHeight;
    const region = plan.profile.region || '';
    const country = plan.profile.country || 'Not specified';
    const location = region ? `${region}, ${country}` : country;
    doc.text(`Location: ${location}`, margin, yPos);
    yPos += lineHeight;
    doc.text(`Created: ${new Date(plan.createdAt).toLocaleDateString()}`, margin, yPos);
    yPos += 10;

    // Section: Executor checklist (addressed / not applicable, optional notes)
    if (checklist.length > 0) {
      sectionNum += 1;
      checkPageBreak(25);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`SECTION ${sectionNum}: EXECUTOR CHECKLIST`, margin, yPos);
      yPos += 10;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      const categoryOrder = getExecutorChecklistCategoryOrder();
      for (const cat of categoryOrder) {
        const items = checklist.filter((i) => i.category === cat);
        if (items.length === 0) continue;

        checkPageBreak(12);
        const catInfo = getChecklistCategoryInfo(cat);
        doc.setFont('helvetica', 'bold');
        doc.text(`— ${catInfo.label} —`, margin, yPos);
        yPos += lineHeight;
        doc.setFont('helvetica', 'normal');

        for (const item of items) {
          const statusLabel = item.status === 'DONE' ? 'Addressed' : item.status === 'NOT_APPLICABLE' ? 'Not applicable' : '—';
          checkPageBreak(includeNotes && item.notes ? lineHeight * 4 : lineHeight + 2);
          doc.text(`${statusLabel}  ${item.title}`, margin + 2, yPos);
          yPos += lineHeight;
          if (includeNotes && item.notes) {
            doc.setFontSize(9);
            doc.setTextColor(80, 80, 80);
            const lines = doc.splitTextToSize(`Notes: ${item.notes}`, doc.internal.pageSize.width - margin * 2 - 10);
            lines.forEach((line: string) => {
              checkPageBreak(lineHeight);
              doc.text(line, margin + 5, yPos);
              yPos += lineHeight;
            });
            doc.setFontSize(10);
            doc.setTextColor(0, 0, 0);
            yPos += 2;
          }
        }
        yPos += 4;
      }
    }

    // Section: Key documents list (if requested and provided)
    if (includeDocs && documents && documents.length > 0) {
      sectionNum += 1;
      checkPageBreak(20);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`SECTION ${sectionNum}: KEY DOCUMENTS`, margin, yPos);
      yPos += 10;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      for (const d of documents) {
        checkPageBreak(lineHeight + 2);
        doc.text(`• ${d.fileName}${d.userLabel ? ` — ${d.userLabel}` : ''}`, margin + 2, yPos);
        yPos += lineHeight;
      }
      yPos += 6;
    }

    // Section: Key contacts (prefer contacts marked isKeyContact; else all)
    const keyContacts =
      contacts.some((c) => c.isKeyContact) ? contacts.filter((c) => c.isKeyContact) : contacts;
    if (keyContacts.length > 0) {
      sectionNum += 1;
      checkPageBreak(20);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`SECTION ${sectionNum}: KEY CONTACTS`, margin, yPos);
      yPos += 10;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      const types = ['BANK', 'INSURANCE', 'EMPLOYER', 'UTILITY', 'ADVISOR', 'ATTORNEY', 'ACCOUNTANT', 'GOVERNMENT', 'OTHER'];
      for (const type of types) {
        const typeContacts = keyContacts.filter((c) => c.type === type);
        if (typeContacts.length === 0) continue;
        checkPageBreak(12);
        const typeInfo = getContactTypeInfo(type as any);
        doc.setFont('helvetica', 'bold');
        doc.text(`— ${typeInfo.label} —`, margin, yPos);
        yPos += lineHeight;
        doc.setFont('helvetica', 'normal');
        for (const contact of typeContacts) {
          checkPageBreak(lineHeight * 3);
          doc.text(contact.name + (contact.organization ? ` — ${contact.organization}` : ''), margin + 2, yPos);
          yPos += lineHeight;
          if (contact.phone) {
            doc.setFontSize(9);
            doc.text(`  Phone: ${contact.phone}`, margin + 2, yPos);
            yPos += lineHeight;
            doc.setFontSize(10);
          }
          if (contact.email) {
            doc.text(`  Email: ${contact.email}`, margin + 2, yPos);
            yPos += lineHeight;
          }
          yPos += 2;
        }
        yPos += 2;
      }
    }

    // Footer — disclaimer
    checkPageBreak(18);
    yPos += 6;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by AfterPassing Guide', margin, yPos);
    yPos += 5;
    doc.text('This material is provided for organizational guidance only and does not constitute legal, financial, or medical advice.', margin, yPos, { maxWidth: doc.internal.pageSize.width - margin * 2 });

    // Confidential watermark on every page
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addConfidentialWatermark(doc);
    }

    const fileName = `Estate_Binder_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}
